// ... existing code ...

export const cropVarieties: Record<string, string[]> = {
  Wheat: ["HD 2967", "HD 3086", "PBW 343", "WH 1105", "DBW 222"],
  Rice: ["IR64", "MTU-1010", "BPT 5204", "Swarna", "Pusa Basmati 1121"],
  Maize: ["HQPM 1", "HM 4", "Suwan-1", "Bio 9637", "DKC 9120"],
  Onion: ["Bhima Shakti", "NHRDF Red", "Agrifound Light Red", "Arka Kalyan", "Pusa Madhavi"],
  Potato: ["Kufri Jyoti", "Kufri Bahar", "Kufri Pukhraj", "Kufri Chipsona-1", "Kufri Sindhuri"],
  Tomato: ["Arka Vikas", "Pusa Ruby", "Vaishali", "Sakthi", "Arka Rakshak"],
  Cabbage: ["Pusa Drumhead", "Golden Acre", "Pride of India", "NS 35", "Copenhagen Market"],
  Chili: ["Pusa Sadabahar", "Kashi Anmol", "Bhaskar", "Arka Lohit", "Tejaswini"],
  Brinjal: ["Pusa Purple Long", "Arka Nidhi", "Arka Kusumkar", "Pusa Ankur", "Pant Samrat"],
  Cucumber: ["Pusa Uday", "Poinsett", "Swarna Poorna", "Kashi Subodh", "Phule Shubhangi"],
  Chickpea: ["JG 11", "KAK 2", "Pusa 362"],
  Moong: ["PDM 139", "SML 668", "ML 818"],
  Arhar: ["BSMR 736", "Maruti", "Asha"]
};

export const regions = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Puducherry",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Ladakh",
  "Lakshadweep"
];